/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubsidyRouteImport } from './routes/subsidy'
import { Route as SolarSystemsRouteImport } from './routes/solar-systems'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as ApplySubsidyRouteImport } from './routes/apply-subsidy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SubsidyRoute = SubsidyRouteImport.update({
  id: '/subsidy',
  path: '/subsidy',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarSystemsRoute = SolarSystemsRouteImport.update({
  id: '/solar-systems',
  path: '/solar-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySubsidyRoute = ApplySubsidyRouteImport.update({
  id: '/apply-subsidy',
  path: '/apply-subsidy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply-subsidy': typeof ApplySubsidyRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-systems': typeof SolarSystemsRoute
  '/subsidy': typeof SubsidyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply-subsidy': typeof ApplySubsidyRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-systems': typeof SolarSystemsRoute
  '/subsidy': typeof SubsidyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply-subsidy': typeof ApplySubsidyRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-systems': typeof SolarSystemsRoute
  '/subsidy': typeof SubsidyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply-subsidy'
    | '/brands'
    | '/contact'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/solar-systems'
    | '/subsidy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply-subsidy'
    | '/brands'
    | '/contact'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/solar-systems'
    | '/subsidy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply-subsidy'
    | '/brands'
    | '/contact'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/solar-systems'
    | '/subsidy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplySubsidyRoute: typeof ApplySubsidyRoute
  BrandsRoute: typeof BrandsRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolarSystemsRoute: typeof SolarSystemsRoute
  SubsidyRoute: typeof SubsidyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subsidy': {
      id: '/subsidy'
      path: '/subsidy'
      fullPath: '/subsidy'
      preLoaderRoute: typeof SubsidyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-systems': {
      id: '/solar-systems'
      path: '/solar-systems'
      fullPath: '/solar-systems'
      preLoaderRoute: typeof SolarSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-subsidy': {
      id: '/apply-subsidy'
      path: '/apply-subsidy'
      fullPath: '/apply-subsidy'
      preLoaderRoute: typeof ApplySubsidyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplySubsidyRoute: ApplySubsidyRoute,
  BrandsRoute: BrandsRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolarSystemsRoute: SolarSystemsRoute,
  SubsidyRoute: SubsidyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
